name: Deploy GitHub Pages

on:
  push:
    # Only run this workflow if changes occur outside the docs folder to avoid loops.
    paths-ignore:
      - 'docs/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Copy build output to docs folder
        run: npm run deploy

      - name: Commit and push docs folder
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: "Deploy [skip ci]: update docs folder"
          add: 'docs'
          branch: main
